name: 和风天气开发平台
description: 提供商业和免费的天气API、天气SDK，开源天气APP，天气插件
timezone: Asia/Shanghai
url: "https://dev.qweather.com"
lang: zh_CN
logo: "/assets/images/logo-s-dark-800.png"
attribution: qweather.com
github: https://github.com/qwd
icp:
  number: 京ICP备15048401号-11
  url: "https://beian.miit.gov.cn"
nis:
  number: 京公网安备11010502042548号
  url: http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010502042548
  icon: "/assets/images/nis-icon.png"
webmaster_verifications:
  google: WFu5M6w9XiYrf3hgUBLxCA1Jrgb_CWTzXTPycVIqngg
  bing: EDFBFE217D2B905D82BE1D5A1BC9AB28
  baidu: code-emsTMHxQLF

defaults:
- scope:
    path: "pages"
    type: "pages"
  values:
    layout: "html"
    lang: zh
    permalink: "/:basename/"
- scope:
    path: "_docs"
    type: "docs"
  values:
    layout: "docs-page"
    lang: zh
    seo:
      type: "DigitalDocument"
- scope:
    path: "_snippets"
  values:
    sitemap: false
collections:
  docs:
    permalink: "/docs/:path/"
    output: true
  snippets:
    permalink: "/snippets/:path/"
    output: true
toc:
  min_level: 2 # default: 1
  max_level: 3 # default: 6
sass:
  sass_dir: _sass
  style: compressed

exclude:
- .idea
- .git
- .gitignore
- .sass-cache
- .jekyll-cache
- .htaccess
- CNAME
- README.md
- LICENSE

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-toc
- jekyll-redirect-from
