name: 和风天气开发者
description: 和风天气强大、现代、易于使用的天气数据服务，包括天气API/SDK，开源天气APP，天气插件等
timezone: Asia/Shanghai
url: "https://dev.heweather.com"
lang: zh_CN
logo: "/assets/images/brand.png"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "html"
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs-page"
      seo:
        type: "DigitalDocument"        

collections:
  docs:
    permalink: "/docs/:path"
    output: true
    
exclude:
- .gitignore
- .jekyll-cache
- README.md

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-toc
- jekyll-redirect-from